/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter */

#ifndef _Included_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
#define _Included_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    exists
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_exists
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    getId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_getId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    create
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_create
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    setPermission
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_setPermission
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    getPermission
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_getPermission
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    setOwnerUserId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_setOwnerUserId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    getOwnerUserId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_getOwnerUserId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    setOwnerGroupId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_setOwnerGroupId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    getOwnerGroupId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_getOwnerGroupId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    getCreatorUserId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_getCreatorUserId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter
 * Method:    getCreatorGroupId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_semaphore_SysVSemaphoreAdapter_getCreatorGroupId
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
