/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter */

#ifndef _Included_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
#define _Included_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    exists
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_exists
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    send
 * Signature: (J[BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_send
  (JNIEnv *, jobject, jlong, jbyteArray, jboolean);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    receive
 * Signature: (JZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_receive
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    setPermission
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_setPermission
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getPermission
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getPermission
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    setOwnerUserId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_setOwnerUserId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getOwnerUserId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getOwnerUserId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    setOwnerGroupId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_setOwnerGroupId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getOwnerGroupId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getOwnerGroupId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    setMaxQueueSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_setMaxQueueSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getMaxQueueSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getMaxQueueSize
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getCreatorUserId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getCreatorUserId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getCreatorGroupId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getCreatorGroupId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getLastSendTime
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getLastSendTime
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getLastReceiveTime
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getLastReceiveTime
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getLastChangeTime
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getLastChangeTime
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getNumberOfMessagesInQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getNumberOfMessagesInQueue
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getLastSendProcessId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getLastSendProcessId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    getLastReceiveProcessId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_getLastReceiveProcessId
  (JNIEnv *, jobject);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter
 * Method:    interrupt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ipc4j_sysv_messagequeue_SysVMessageQueueAdapter_interrupt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
